apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: rmdocker42/todo-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
          - name: DB_NAME
            value: todo_db
          - name: DB_USER
            value: todo_user
          - name: DB_PASSWORD
            value: secretpassword
          - name: DB_HOST
            value: postgres
          - name: DB_PORT
            value: "5432"