echo Starting Minikube...
.\minikube-windows-amd64.exe start --driver=docker

echo Deploying Postgres...
kubectl apply -f postgres.yaml

echo Waiting for Postgres pod to be Running...
kubectl wait --for=condition=ready pod -l app=postgres --timeout=120s

echo Running migration job...
kubectl apply -f job-migrate.yaml
kubectl wait --for=condition=complete job/todo-app-migrate --timeout=120s

echo Deploying Django app...
kubectl apply -f deployment.yaml
kubectl apply -f service.yaml

echo Waiting for todo-app pod to be Ready...
kubectl wait --for=condition=ready pod -l app=todo-app --timeout=120s

echo Opening application...
.\minikube-windows-amd64.exe service todo-app-service