# Generated by Django 5.2.6 on 2025-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0003_task_completed_at_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Élevée'), ('2', 'Moyenne'), ('3', 'Faible')], db_index=True, default='2', max_length=6),
        ),
    ]
